openapi: 3.0.3
info:
  title: Rails Url Shortener
  description: A small application for making short urls
  contact:
    email: rails-url-shortener@truggeri.com
  license:
    name: MIT
    url: https://github.com/truggeri/rails-url-shortener/blob/main/LICENSE
  version: 0.1.0
externalDocs:
  description: See our Github
  url: https://github.com/truggeri/rails-url-shortener/
tags:
  - name: use
    description: Using a short URL
  - name: admin
    description: Routes for managing URL shorts
  - name: ops
    description: Routes used for the operation of the app
paths:
  /:
    post:
      tags:
        - admin
      summary: Create a new short URL
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - full_url
              type: object
              properties:
                full_url:
                  description: The target URL
                  example: https://petfinder.com
                  type: string
                short_url:
                  description: The desired short URL. All characters (a-z) are lower cased
                  example: doggo
                  type: string
      responses:
        200:    
          description: The short URL was successfully created
        400:
          description: The provided params are not valid
        401:
          description: The provided authentication is not authorized to remove this short URL
  /{short_url}:
    get:
      tags:
      - use
      summary: Short URL
      description: A request with a short URL.
      parameters:
        - name: short_url
          in: path
          description: The short URL code
          required: true
          schema:
            type: string
      responses:
        302:
          description: Redirect to the full URL
          headers:
            Location:
              schema:
                type: string
              description: The full URL
        404:
          description: Short URL could not be found
    delete:
      tags:
        - admin
      summary: Delete a short URL
      description: Remove a short URL from use
      parameters:
        - name: short_url
          in: path
          description: The short URL code
          required: true
          schema:
            type: string
      responses:
        200:
          description: The short URL was successfully removed
        401:
          description: The provided authentication is not authorized to remove this short URL
        404:
          description: Short URL could not be found
  /health:
    get:
      tags:
      - ops
      summary: Health check
      description: Simple route used to ensure the app is alive
      responses:
        200:
          description: Healthy