openapi: 3.0.3
info:
  title: Rails Url Shortener
  description: A small application for making short urls
  contact:
    email: rails-url-shortener@truggeri.com
  license:
    name: MIT
    url: https://github.com/truggeri/rails-url-shortener/blob/main/LICENSE
  version: 0.1.0
externalDocs:
  description: See our Github
  url: https://github.com/truggeri/rails-url-shortener/
tags:
  - name: use
    description: Using a short URL
  - name: admin
    description: Routes for creating and deleting shorts
  - name: ops
    description: Routes used for the operation of the app
paths:
  /{short_url}:
    get:
      tags:
      - use
      summary: Short URL
      description: A request with a short URL.
      parameters:
        - name: short_url
          in: path
          description: Status values that need to be considered for filter
          required: true
          schema:
            type: string
      responses:
        302:
          description: Redirect to the full URL
          headers:
            Location:
              schema:
                type: string
              description: The full URL
        404:
          description: Short URL could not be found
  /health:
    get:
      tags:
      - ops
      summary: Health check
      description: Simple route used to ensure the app is alive
      responses:
        200:
          description: Healthy